apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.dest_server }}
  project: default
  ignoreDifferences:
  - group: "admissionregistration.k8s.io/v1"
    kind: "MutatingWebhookConfiguration"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: "*"
    kind: "*"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'

  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.29.1"
    helm : 
      values: |
{{ include "helmValues.vault" . | indent 8 }}